### ISSUE TITLE
Looking for Dockerfiles of Walki12/* Images

### ISSUE THREAD

**Issue by croonwolterendros** [wakonp/jupyterhub-deploy-swarm#3]
Hello!
Where can i find the Dockerfiles of all the Walki12 images? 
I can't seem to start the nfs server and I'd like to see what's going on in that image. Besides I also want the ability to make changes to the image files.
Hope you can help me a bit further,

Anouar Manders

**Comment by wakonp** [comment]
Hi,
Just look for all the Dockerfiles in this repository.

https://github.com/wakonp/jupyterhub-deploy-swarm/blob/master/Dockerfile - Jupyterhub

https://github.com/wakonp/jupyterhub-deploy-swarm/blob/master/fhj-notebooks/student-notebook/Dockerfile.studentnotebook - Studentnotebook

https://github.com/wakonp/jupyterhub-deploy-swarm/blob/master/fhj-notebooks/teacher-notebook/Dockerfile.teachernotebook - Teachernotebook

I hope that solves your issue.
